name: flutter_deck_web_client
description: A Web client for the flutter_deck package that allows you to control the presentation from another browser tab or window.
version: 0.1.1
homepage: https://github.com/mkobuolys/flutter_deck
repository: https://github.com/mkobuolys/flutter_deck/tree/main/packages/flutter_deck_web_client
issue_tracker: https://github.com/mkobuolys/flutter_deck/issues
topics:
  - flutterdeck
  - presentation
  - slides
funding:
  - https://github.com/sponsors/mkobuolys

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_deck_client: ^0.1.0
  web: ^0.5.1

dev_dependencies:
  test: ^1.25.8
  very_good_analysis: ^6.0.0
