name: flutter_deck

packages:
  - packages/**

ignore:
  - packages/**/example

scripts:
  analyze:
    exec: dart analyze .
  format:
    exec: dart format --set-exit-if-changed .
  test:
    exec: flutter test
