name: flutter_deck
description: A lightweight, customizable, and easy-to-use framework to create presentations in Flutter.
version: 0.10.0
homepage: https://github.com/mkobuolys/flutter_deck
repository: https://github.com/mkobuolys/flutter_deck
issue_tracker: https://github.com/mkobuolys/flutter_deck/issues
topics:
  - flutterdeck
  - presentation
  - slides
funding:
  - https://github.com/sponsors/mkobuolys

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  go_router: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
